In [1]:
#Create a list of squares of all even numbers from 1 to 20.

result = []

def even_squares(start, end):
    """Return a list of squares of all even numbers in the given range."""
    for x in range(start, end + 1):
        if x % 2 == 0:
            result.append(x**2)
            

# Call the function for numbers 1 to 20
even_squares(1, 20)
print(result)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [2]:
#Given a list of student names and scores, create a dictionary and print students who scored above 80.

student_scores = [
{
    "name": "John",
    "score": 90
},  

{
    "name": "Ana",
    "score": 49
},
{"name": "Mike", "score": 82},
{"name": "Sara", "score": 76}
]

print("Students who scored above 80:")
for student in student_scores:
    if student["score"] > 80:
        print(f"{student['name']}: {student['score']}")

Students who scored above 80:
John: 90
Mike: 82


In [ ]:
#Write a Python function `get_top_k_docs(query, embeddings, k)` that returns top-k cosine-similar documents.
import numpy as np

from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")

def get_top_k_docs(query, embeddings, k):
    query_vector = model.encode([query])[0]
    similarities = model.similarity(query_vector, embeddings)

    # Ensure it's a 1D numpy array
    similarities = np.asarray(similarities).squeeze()


    # Now get top 3
    top_3_indices = np.argsort(similarities)[::-1][:k]
    top_scores = similarities[top_3_indices]
    return top_scores

In [ ]:
#Write a function that reads a text file and returns its length, handling the case where the file doesn’t exist.
def get_file_length(file_path):
    """
    Reads a text file and returns its length (number of characters).
    If the file does not exist, returns None and prints an error message.
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read()
            return len(content)
    except FileNotFoundError:
            print(f"Error: The file '{file_path}' does not exist.")
            return None

# Example usage
file_path = "/Users/chandurajana/Documents/Chandu_Training/2025_09_GenAI_chandu/session4/read_txt_file.txt"
length = get_file_length(file_path)

if length is not None:
    print(f"The length of the file is {length} characters.")


The length of the file is 2181 characters.


In [4]:
#Generate random 5D vectors using NumPy and compute pairwise cosine similarity between them.
import numpy as np

# Step 1: Random 4x5 vectors
vectors = np.random.rand(4,5)
print("4 Random 5D vector:", vectors)

# Step 2: Normalize
norms = np.linalg.norm(vectors, axis=1, keepdims=True)
vectors_normalized = vectors / norms

# Step 3: Cosine similarity
cosine_similarity = np.dot(vectors_normalized, vectors_normalized.T)
print("\nPairwise Cosine Similarity:\n", cosine_similarity)

4 Random 5D vector: [[0.4415906  0.52876682 0.60582587 0.01272328 0.96326205]
 [0.8569122  0.24371546 0.58265719 0.12103749 0.88565445]
 [0.49923548 0.4514847  0.89163896 0.54916144 0.38529196]
 [0.94212829 0.95738577 0.68539021 0.29305219 0.71541849]]

Pairwise Cosine Similarity:
 [[1.         0.92740811 0.79461974 0.90066285]
 [0.92740811 1.         0.8088025  0.89536299]
 [0.79461974 0.8088025  1.         0.88317725]
 [0.90066285 0.89536299 0.88317725 1.        ]]
